### ISSUE TITLE
step_func missing documentation exp_hydro

### ISSUE THREAD

**Issue by olivierbonte** [chooron/HydroModels.jl#2]
The function `step_func` is not defined the tutorial on building exp hydro (https://github.com/chooron/HydroModels.jl/blob/main/docs/src/implements/build_exphydro_model_en.md), which makes running the example not feasible.

**Comment by chooron** [comment]
Hello, I apologize for not checking this issue. This step_func is a function used for smoothing the judgment process:
```
step_func(x) = (tanh(5.0 * x) + 1.0) * 0.5
```

**Comment by olivierbonte** [comment]
Thank you for the clarification! With the updated documentation from https://github.com/chooron/HydroModels.jl/commit/7727d7dbe0d9c6fb93d6f01da19533aa939222c0 it is much clearer
